apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    name: "{{ .Chart.Name }}"
